# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgCtGpUvImaA1pQM4M7jtHpEG3P5lsyf

**1. General Idea**
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

salaries = pd.read_csv('https://richardson.byu.edu/220/ds_salary.csv')
frequency_distribution = salaries["salary"].value_counts().sort_index()

#histogam
# Header 1
plt.figure(figsize=(9, 5))
plt.hist(salaries["salary"], bins=10, edgecolor='black')
plt.title(f'Salaries of Data Scientists')
plt.xlabel("Annual Income (In Dollars)")
plt.ylabel('Frequency')
plt.show()

#Box Plot
plt.figure(figsize=(7, 3))
plt.boxplot(salaries["salary"], vert=False)
plt.title(f'Salaries of Data Scientists')
plt.xlabel("Annual Salary (In Dollars)")
plt.show()

print("\n")
minimum = np.min(salaries["salary"])
median = np.median(salaries["salary"])
maximum = np.max(salaries["salary"])
print(f"Min: ${minimum}, Median: ${median}, Max: ${maximum}")

"""Looking at the data from a very basic analysis we can see that the average salary is clustered around $100000.

The data is also heavily skewed to the right as the tail leads up towards $700000.

---

**2. How does experience affect salary?**
"""

plt.figure(figsize=(7, 4))
salaries.boxplot(column="salary", by='experience_level', vert=False, grid=False)

"""Experience Level EN:Entry-level/Junior, MI:Mid-level/Intermediate, SE:Senior-level/Expert, EX:Executive-level/Director

It's clear that having the experience of an Entry level results in the lowest salary as shown in this plot. It has the lowest average and the least possible spread.
There was quite a bit of variation in the salaries in senior-level employees. They had the widest range of values and the highest salary recorded. That high value does seem to an outlier, and definitely doesn't represent the majority of employees who are senior-level who on average make less than those with an executive title. Those with executive experience levels generally make the most money of all experience levels.

**3. How does company size affect salary?**
"""

plt=salaries.boxplot(column="salary", by='company_size', vert=False, grid=False)

"""The size of the company does appear to effect the potential salary of an employee though not as dramatic as Experience level or Job Title. Those at small companies make on average less than those at Medium or Large companies. Employees at Medium and Large companies have incredibly similar salary rates that are on average higher than those at small companies.

**4. How does Job Title affect salary?**
"""

result=pd.Series(salaries['job_title'])


temp_table=salaries[['job_title', 'salary']]

def match(new_name, table):
  old=result.str.contains(pat=new_name)

  for i, value in enumerate(old):
    if value:
      if new_name=="Analy":
        temp_table['job_title'][i]="Analytics"
      else:
        temp_table['job_title'][i]=new_name

#Narrow the table
match('Data Science', temp_table)
match('Analy', temp_table)
match('Scientist', temp_table)
match('Engineer', temp_table)
match('Machine Learning', temp_table)

temp_table.boxplot(column='salary', by='job_title', vert=False, grid = False)

"""Consistently high paying job titles include
Data Science, Data Specialist, Head of Data, 3D Computer Vision Researcher, or Data Architect. These jobs have higher average salaries than the other job titles. 3D Computer Vision Researcher has the highest average, but we do have to consider that there is only one point of data for it, so drawing any wider conclusions about the title is difficult.

Those who work under a title with Scientist or Engineer have the widest spreads of data and the highest listed salaries of all. However they do still have overall average or low salaries. These two groups are pulled from many slightly different job titles so this most likely acconts for the wide range of values.

Overall while job title does affect the salary it does appear that on average almost all of the job titles median salaries are from about 100000 dollars to 200000 dollars. So it appears that there are other factors that could be used to get a better idea of relative salary.

**5. Are there interactions between the relationships, meaning do these relationships overlap?
Create a two way table where you look at important statistics as the intersection of two
variables, e.g. a table with job title on the left, company size on top, and each cell is the
mean salary for each job title/company size interaction.**
"""

#cross tab table?
experience_level_company_size = pd.crosstab(salaries['company_size'],salaries['experience_level'], values=salaries['salary'], aggfunc='mean')

print(experience_level_company_size)

"""The relationship between experience level, company size, and salary show as when the experience level increases and/or the company size gets bigger, the salary goes up as well."""

experience_level_employment_type = pd.crosstab(salaries['employment_type'],salaries['experience_level'], values=salaries['salary'], aggfunc='mean')

print(experience_level_employment_type)

"""Employment Type PT:Part-time, FT:Full-time, CT:Contract, FL:Freelance

Experience Level EN:Entry-level/Junior, MI:Mid-level/Intermediate, SE:Senior-level/Expert, EX:Executive-level/Director

There doesn't seem to be any discenable pattern for the resulting salary from the combination of experience level and employment type.

The only pattern that can be seen is full-time workers of higher experience earn more money.


"""

company_size_employment_type = pd.crosstab(salaries['company_size'],salaries['employment_type'], values=salaries['salary'], aggfunc='mean')

print(company_size_employment_type)

"""Employment Type PT:Part-time, FT:Full-time, CT:Contract, FL:Freelance

There does not seem to be much connection between employment type and company size. Similar to with experience level we can notice that full time workers increase in mean salary as the company size increase. Any other conclusions are difficult to draw.

**6. Clearly list all significant relationships you discovered.**

1. Workers at Medium or Large companies on average make more money than those working at small companies.

2. Full time workers always saw an increase in salary with a higher experience level or a larger company.

3. While different job titles did have different average salaries it appears that for individual positions either more experience or company size afftected the salary more.

4. Experience level was a large factor in averge salary as a higher experience level showed a higher average salary.
"""